complete -xc paur -a "disowned" -d "Display list of disowned files"
complete -xc paur -a "in" -d "pacaur -S; Install specific package(s) from the repositories"
complete -xc paur -a "ins" -d "pacaur -S; Display list of disowned files"
complete -xc paur -a "list" -d "pacaur -Qe;	List installed packages, even those installed from AUR (they're tagged as \"local\")"
complete -xc paur -a "loc" -d "pacaur -Qi;	Display information about a given package in the local database"
complete -xc paur -a "locs" -d "pacaur -Qs;	Search for package(s) in the local database"
complete -xc paur -a "upd" -d "pacaur -Sy;	Update and refresh the local package database against repositories"
complete -xc paur -a "upg" -d "pacaur -Syua;	Synchronize with repositories before upgrading packages (AUR packages too) that are out of date on the local system"
complete -xc paur -a "reps" -d "pacaur -Ss;	Search for package(s) in the repositories"
